{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harvester-pusher-chart.secretName" . }}
  labels:
    {{- include "harvester-pusher-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}
  harvester-endpoint: {{ .Values.credentials.endpoint }}
{{- end -}}
