apiVersion: batch/v1
kind: CronJob
metadata:
  name: harvester-metrics-job
  namespace: cattle-monitoring-system
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-pusher
            image: docker-nivola.ecosis.csi.it/docker-nivola/harvester-metrics-pusher:1.0.0
            volumeMounts:
            - name: creds
              mountPath: /secrets
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: creds
            secret:
              secretName: harvester-creds
 